# Generated by Django 5.1.4 on 2025-04-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('genre', models.CharField(default='General', max_length=100)),
                ('image', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
