# Generated by Django 5.1.4 on 2025-03-03 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_quote_genre_quote_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='img',
            new_name='image',
        ),
    ]
